version: '3'
services:
  app:
    image: julenrecio/entrega:v1
    depends_on:
      - db
    ports:
      - 8080:8080
  db:
    image: postgres
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: julen2000
      POSTGRES_DB: bbdd
      POSTGRES_HOST: db
    ports:
      - 5432:5432